var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d696e6b5._.js")
R.c("server/chunks/ssr/_10c96619._.js")
R.c("server/chunks/ssr/1629d_next_dist_esm_build_templates_app-page_8dd76d3a.js")
R.c("server/chunks/ssr/[root-of-the-server]__fe53d8a0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03cd63cf._.js")
R.c("server/chunks/ssr/1629d_next_dist_8dc31fba._.js")
R.c("server/chunks/ssr/example_react-next-demo_app_6b027ed7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0508dc71._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_b01b33e4._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_forbidden_4cab2078.js")
R.c("server/chunks/ssr/e547e_react-next-demo__next-internal_server_app__not-found_page_actions_71f51eab.js")
R.m(58724)
module.exports=R.m(58724).exports
