var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__aadd7472._.js")
R.c("server/chunks/ssr/_10c96619._.js")
R.c("server/chunks/ssr/_b83d7d38._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8adb44b7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03cd63cf._.js")
R.c("server/chunks/ssr/1629d_next_dist_8dc31fba._.js")
R.c("server/chunks/ssr/example_react-next-demo_app_6b027ed7._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_global-error_0d5cb623.js")
R.c("server/chunks/ssr/[root-of-the-server]__0508dc71._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_b01b33e4._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_forbidden_4cab2078.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_unauthorized_b8fbdcad.js")
R.c("server/chunks/ssr/example_react-next-demo__next-internal_server_app_page_actions_5cf2fd97.js")
R.m(36052)
module.exports=R.m(36052).exports
